# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('etiqueta', models.SlugField(verbose_name='Etiqueta')),
            ],
        ),
    ]
